In [3]:
import pandas as pd
import numpy as np
import sys
import seaborn as sns
np.set_printoptions(threshold=sys.maxsize)
sns.set() 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.reset_option('future.no_silent_downcasting', True)
import warnings
warnings.filterwarnings('ignore')

In [177]:
data = pd.read_csv("D:\\NCI Docs\\NCI LECS\\Analytics programming and data visualization\\Group project\\owid-energy-data.csv")
data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.87,1.550,NaN,569.557,NaN,NaN,NaN,NaN,NaN,76.03,NaN,NaN,NaN,NaN,20.081,NaN,378.61,378.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.36,NaN,NaN,80.653,NaN,NaN,NaN,NaN,NaN,164.26,NaN,NaN,NaN,NaN,NaN,43.385,NaN,215.64,NaN,NaN,NaN,NaN,50.45,NaN,13.325,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,65.07,NaN,NaN,NaN,NaN,NaN,17.187,NaN,NaN,22.80,16.93,NaN,NaN,NaN,NaN,NaN,6.022,4.472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.46,1.596,NaN,567.642,NaN,NaN,NaN,NaN,NaN,86.26,NaN,NaN,NaN,NaN,21.307,NaN,404.85,404.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.66,NaN,NaN,80.934,NaN,NaN,NaN,NaN,NaN,190.41,NaN,NaN,NaN,NaN,NaN,47.032,NaN,229.81,NaN,NaN,NaN,NaN,54.33,NaN,13.420,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,50.99,NaN,NaN,NaN,NaN,NaN,12.595,NaN,NaN,22.86,16.40,NaN,NaN,NaN,NaN,NaN,5.647,4.051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.62,1.528,NaN,570.212,NaN,NaN,NaN,NaN,NaN,93.43,NaN,NaN,NaN,NaN,21.568,NaN,433.19,433.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.67,NaN,NaN,82.336,NaN,NaN,NaN,NaN,NaN,208.92,NaN,NaN,NaN,NaN,NaN,48.228,NaN,247.01,NaN,NaN,NaN,NaN,53.29,NaN,12.302,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,54.32,NaN,NaN,NaN,NaN,NaN,12.540,NaN,NaN,23.23,16.61,NaN,NaN,NaN,NaN,NaN,5.363,3.834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.45,1.626,NaN,574.699,NaN,NaN,NaN,NaN,NaN,102.01,NaN,NaN,NaN,NaN,22.261,NaN,458.24,458.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.84,NaN,NaN,83.328,NaN,NaN,NaN,NaN,NaN,226.51,NaN,NaN,NaN,NaN,NaN,49.430,NaN,263.35,NaN,NaN,NaN,NaN,53.21,NaN,11.612,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,53.32,NaN,NaN,NaN,NaN,NaN,11.636,NaN,NaN,23.19,15.74,NaN,NaN,NaN,NaN,NaN,5.061,3.435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.672,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.40,1.692,NaN,581.420,NaN,NaN,NaN,NaN,NaN,115.01,NaN,NaN,NaN,NaN,23.161,NaN,496.56,496.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.60,NaN,NaN,84.300,NaN,NaN,NaN,NaN,NaN,244.16,NaN,NaN,NaN,NaN,NaN,49.170,NaN,288.71,NaN,NaN,NaN,NaN,52.99,NaN,10.671,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,59.43,NaN,NaN,NaN,NaN,NaN,11.968,NaN,NaN,24.97,16.57,NaN,NaN,NaN,NaN,NaN,5.029,3.337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.700,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

## Data Pre-processing

In [180]:
data = data[data['year'] >= 1970]

In [182]:
data.shape

(13427, 129)

In [184]:
data.isna().sum()

country                                             0
year                                                0
iso_code                                         3105
population                                       2430
gdp                                              5507
biofuel_cons_change_pct                         11637
biofuel_cons_change_twh                         10703
biofuel_cons_per_capita                         11092
biofuel_consumption                             10641
biofuel_elec_per_capita                          7857
biofuel_electricity                              7593
biofuel_share_elec                               7616
biofuel_share_energy                            10724
carbon_intensity_elec                            7592
coal_cons_change_pct                             8447
coal_cons_change_twh                             8337
coal_cons_per_capita                             9015
coal_consumption                                 8313
coal_elec_per_capita                             7357
coal_electricity                                 6742
coal_prod_change_pct                             8547
coal_prod_change_twh                             3344
coal_prod_per_capita                             4194
coal_production                                  3179
coal_share_elec                                  6765
coal_share_energy                                8850
electricity_demand                               7564
electricity_generation                           6016
electricity_share_energy                         9467
energy_cons_change_pct                           2067
energy_cons_change_twh                           1874
energy_per_capita                                3120
energy_per_gdp                                   5958
fossil_cons_change_pct                           8714
fossil_cons_change_twh                           8714
fossil_elec_per_capita                           7314
fossil_electricity                               6699
fossil_energy_per_capita                         9372
fossil_fuel_consumption                          8671
fossil_share_elec                                6727
fossil_share_energy                              8850
gas_cons_change_pct                              8532
gas_cons_change_twh                              8480
gas_consumption                                  8444
gas_elec_per_capita                              7429
gas_electricity                                  6814
gas_energy_per_capita                            9145
gas_prod_change_pct                              7804
gas_prod_change_twh                              3122
gas_prod_per_capita                              4072
gas_production                                   2958
gas_share_elec                                   6837
gas_share_energy                                 8850
greenhouse_gas_emissions                         7564
hydro_cons_change_pct                            8603
hydro_cons_change_twh                            8305
hydro_consumption                                8287
hydro_elec_per_capita                            5786
hydro_electricity                                4820
hydro_energy_per_capita                          8989
hydro_share_elec                                 6166
hydro_share_energy                               8850
low_carbon_cons_change_pct                       8542
low_carbon_cons_change_twh                       8305
low_carbon_consumption                           8287
low_carbon_elec_per_capita                       6364
low_carbon_electricity                           5547
low_carbon_energy_per_capita                     8989
low_carbon_share_elec                            6353
low_carbon_share_energy                          8850
net_elec_imports                                 7852
net_elec_imports_share_demand                    7880
nuclear_cons_change_pct                         11041
nuclear_cons_change_twh                          6977
nuclear_consumption                              6936
nuclear_elec_per_capita                          5099
nuclear_electricity                              4229
nuclear_energy_per_capita                        7542
nuclear_share_elec                               6225
nuclear_share_energy                             8974
oil_cons_change_pct                              8077
oil_cons_change_twh                              8077
oil_consumption                                  8063
oil_elec_per_capita                              7394
oil_electricity                                  6779
oil_energy_per_capita                            8765
oil_prod_change_pct                              7432
oil_prod_change_twh                              2941
oil_prod_per_capita                              4014
oil_production                                   2792
oil_share_elec                                   6802
oil_share_energy                                 8850
other_renewable_consumption                      8532
other_renewable_electricity                      5186
other_renewable_exc_biofuel_electricity          8157
other_renewables_cons_change_pct                 9865
other_renewables_cons_change_twh                 8598
other_renewables_elec_per_capita                 6117
other_renewables_elec_per_capita_exc_biofuel     8421
other_renewables_energy_per_capita               9199
other_renewables_share_elec                      6234
other_renewables_share_elec_exc_biofuel          8180
other_renewables_share_energy                    9162
per_capita_electricity                           6787
primary_energy_consumption                       1699
renewables_cons_change_pct                       8548
renewables_cons_change_twh                       8305
renewables_consumption                           8287
renewables_elec_per_capita                       6364
renewables_electricity                           5435
renewables_energy_per_capita                     8989
renewables_share_elec                            6275
renewables_share_energy                          8850
solar_cons_change_pct                           11196
solar_cons_change_twh                            8857
solar_consumption                                8780
solar_elec_per_capita                            6291
solar_electricity                                5362
solar_energy_per_capita                          9445
solar_share_elec                                 6244
solar_share_energy                               9390
wind_cons_change_pct                            10919
wind_cons_change_twh                             8803
wind_consumption                                 8729
wind_elec_per_capita                             6270
wind_electricity                                 5340
wind_energy_per_capita                           9395
wind_share_elec                                  6230
wind_share_energy                                9344
dtype: int64

In [186]:
#print(data.shape)

In [188]:
#columns = data.columns.tolist()

In [190]:
#for col in columns:
#    data=data[[col for col in df if data[col].isnull().sum() < 15000]]

In [192]:
#data.shape

In [194]:
#data.head()

In [196]:
# Drop rows(countries) where population count is not available
df = data.dropna(subset=['population'])

In [198]:
df.shape

(10997, 129)

In [200]:
df_1 = df.dropna(subset=['iso_code'])

In [202]:
df_1.shape

(10242, 129)

In [204]:
df_1['country'] = df_1['country'].str.strip().str.title()

In [206]:
data_year = df_1.groupby("year")

In [208]:
data_year['year'].value_counts()

year
1970    102
1971    101
1972    101
1973    101
1974    101
1975    101
1976    101
1977    101
1978    101
1979    101
1980    196
1981    195
1982    195
1983    195
1984    195
1985    201
1986    202
1987    202
1988    202
1989    202
1990    208
1991    207
1992    213
1993    213
1994    214
1995    214
1996    214
1997    215
1998    215
1999    215
2000    217
2001    217
2002    217
2003    218
2004    218
2005    218
2006    218
2007    218
2008    218
2009    218
2010    218
2011    217
2012    218
2013    218
2014    218
2015    218
2016    218
2017    218
2018    218
2019    218
2020    218
2021    218
2022    210
2023    116
Name: count, dtype: int64

In [210]:
df_2 = df_1[df_1['year'] >= 2000]

In [212]:
df_2.shape

(5118, 129)

In [220]:
import mysql.connector

In [222]:
conn = mysql.connector.connect(host="localhost", user="root", password="Anirane15@isro",database="")
cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS energy_db")

print("Database 'energy_db' created successfully!")

# Close connection
cursor.close()
conn.close()

Database 'energy_db' created successfully!

In [224]:
conn = mysql.connector.connect(host="localhost", user="root", password="Anirane15@isro", database="energy_db")
cursor = conn.cursor()
# Create the 'countries' table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS countries (
        iso_code VARCHAR(10) UNIQUE PRIMARY KEY,
        country_name VARCHAR(255) UNIQUE
    )
""")

In [226]:
unique_countries = df_2[['country', 'iso_code']].drop_duplicates()
unique_countries = unique_countries.replace({np.nan: None})
for index, row in unique_countries.iterrows():
    cursor.execute("INSERT IGNORE INTO countries (country_name, iso_code) VALUES (%s, %s)", (row['country'], row['iso_code']))

In [228]:
conn.commit()

In [234]:
columns = df.columns.to_list()
columns

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

In [240]:
columns_selected = ['country','year','iso_code','population','gdp','biofuel_cons_per_capita','biofuel_consumption','biofuel_electricity','biofuel_share_elec','carbon_intensity_elec','coal_cons_per_capita','coal_consumption','coal_electricity','coal_production','coal_share_elec','electricity_demand',
'electricity_generation','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','gas_consumption','gas_energy_per_capita','gas_production',
'gas_share_elec','greenhouse_gas_emissions','low_carbon_consumption','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','nuclear_consumption','nuclear_electricity','nuclear_energy_per_capita',
'nuclear_share_elec','oil_consumption','oil_electricity','oil_energy_per_capita','oil_production','oil_share_elec','other_renewable_consumption','other_renewable_electricity','other_renewables_energy_per_capita',
'other_renewables_share_elec','renewables_consumption','renewables_electricity','renewables_energy_per_capita','renewables_share_elec']

In [244]:
new_df = df_2[columns_selected]
new_df.head()

,country,year,iso_code,population,gdp,biofuel_cons_per_capita,biofuel_consumption,biofuel_electricity,biofuel_share_elec,carbon_intensity_elec,coal_cons_per_capita,coal_consumption,coal_electricity,coal_production,coal_share_elec,electricity_demand,electricity_generation,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,gas_consumption,gas_energy_per_capita,gas_production,gas_share_elec,greenhouse_gas_emissions,low_carbon_consumption,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,nuclear_consumption,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,oil_consumption,oil_electricity,oil_energy_per_capita,oil_production,oil_share_elec,other_renewable_consumption,other_renewable_electricity,other_renewables_energy_per_capita,other_renewables_share_elec,renewables_consumption,renewables_electricity,renewables_energy_per_capita,renewables_share_elec
124,Afghanistan,2000,AFG,19542986.0,1.128379e+10,NaN,NaN,0.0,0.0,250.000,NaN,NaN,0.00,0.006,0.000,0.57,0.48,0.17,NaN,NaN,35.417,NaN,NaN,2.495,0.0,0.12,NaN,0.31,NaN,64.583,NaN,0.0,NaN,0.0,NaN,0.17,NaN,0.0,35.417,NaN,0.0,NaN,0.0,NaN,0.31,NaN,64.583
125,Afghanistan,2001,AFG,19688634.0,1.102127e+10,NaN,NaN,0.0,0.0,217.391,NaN,NaN,0.04,0.151,5.797,0.78,0.69,0.19,NaN,NaN,27.536,NaN,NaN,0.542,0.0,0.15,NaN,0.50,NaN,72.464,NaN,0.0,NaN,0.0,NaN,0.15,NaN,0.0,21.739,NaN,0.0,NaN,0.0,NaN,0.50,NaN,72.464
126,Afghanistan,2002,AFG,21000258.0,1.880487e+10,NaN,NaN,0.0,0.0,169.014,NaN,NaN,0.04,0.122,5.634,0.81,0.71,0.15,NaN,NaN,21.127,NaN,NaN,0.542,0.0,0.12,NaN,0.56,NaN,78.873,NaN,0.0,NaN,0.0,NaN,0.11,NaN,0.0,15.493,NaN,0.0,NaN,0.0,NaN,0.56,NaN,78.873
127,Afghanistan,2003,AFG,22645136.0,2.107434e+10,NaN,NaN,0.0,0.0,241.758,NaN,NaN,0.09,0.203,9.890,1.01,0.91,0.28,NaN,NaN,30.769,NaN,NaN,0.217,0.0,0.22,NaN,0.63,NaN,69.231,NaN,0.0,NaN,0.0,NaN,0.19,NaN,0.0,20.879,NaN,0.0,NaN,0.0,NaN,0.63,NaN,69.231
128,Afghanistan,2004,AFG,23553554.0,2.233257e+10,NaN,NaN,0.0,0.0,227.848,NaN,NaN,0.06,0.197,7.595,0.89,0.79,0.23,NaN,NaN,29.114,NaN,NaN,0.217,0.0,0.18,NaN,0.56,NaN,70.886,NaN,0.0,NaN,0.0,NaN,0.17,NaN,0.0,21.519,NaN,0.0,NaN,0.0,NaN,0.56,NaN,70.886

In [246]:
new_df.shape

(5118, 47)

In [254]:
# Removing rows for which all the column values are nan
nf = new_df.dropna(subset=new_df.drop(columns="country").columns, how="all")
nf.shape

(5118, 47)

In [320]:
# Creating a table for maintaining the various energy statistics
conn = mysql.connector.connect(host="localhost", user="root", password="Anirane15@isro", database="energy_db")
cursor = conn.cursor()
# Create the 'energy_stats' table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS energy_stats (
        iso_code VARCHAR(10),
        year INT NOT NULL,
        population BIGINT,
        gdp BIGINT,
        biofuel_cons_per_capita FLOAT, biofuel_consumption FLOAT, biofuel_electricity FLOAT, biofuel_share_elec FLOAT, carbon_intensity_elec FLOAT, coal_cons_per_capita FLOAT, coal_consumption FLOAT, coal_electricity FLOAT, coal_production FLOAT, coal_share_elec FLOAT, electricity_demand FLOAT,
        electricity_generation FLOAT, fossil_electricity FLOAT, fossil_energy_per_capita FLOAT, fossil_fuel_consumption FLOAT, fossil_share_elec FLOAT, gas_consumption FLOAT, gas_energy_per_capita FLOAT, gas_production FLOAT,
        gas_share_elec FLOAT, greenhouse_gas_emissions FLOAT, low_carbon_consumption FLOAT, low_carbon_electricity FLOAT, low_carbon_energy_per_capita FLOAT, low_carbon_share_elec FLOAT, nuclear_consumption FLOAT, nuclear_electricity FLOAT, nuclear_energy_per_capita FLOAT,
        nuclear_share_elec FLOAT, oil_consumption FLOAT, oil_electricity FLOAT, oil_energy_per_capita FLOAT, oil_production FLOAT, oil_share_elec FLOAT, other_renewable_consumption FLOAT, other_renewable_electricity FLOAT, other_renewables_energy_per_capita FLOAT,
        other_renewables_share_elec FLOAT, renewables_consumption FLOAT, renewables_electricity FLOAT, renewables_energy_per_capita FLOAT, renewables_share_elec FLOAT,
        FOREIGN KEY (iso_code) REFERENCES countries(iso_code),
        PRIMARY KEY (iso_code, year)
    )
""")

In [ ]:
energy_df = nf[['iso_code','year','population','gdp','biofuel_cons_per_capita','biofuel_consumption','biofuel_electricity','biofuel_share_elec','carbon_intensity_elec','coal_cons_per_capita','coal_consumption','coal_electricity','coal_production','coal_share_elec','electricity_demand',
'electricity_generation','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','gas_consumption','gas_energy_per_capita','gas_production',
'gas_share_elec','greenhouse_gas_emissions','low_carbon_consumption','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','nuclear_consumption','nuclear_electricity','nuclear_energy_per_capita',
'nuclear_share_elec','oil_consumption','oil_electricity','oil_energy_per_capita','oil_production','oil_share_elec','other_renewable_consumption','other_renewable_electricity','other_renewables_energy_per_capita',
'other_renewables_share_elec','renewables_consumption','renewables_electricity','renewables_energy_per_capita','renewables_share_elec']].drop_duplicates()
energy_df = energy_df.dropna(subset=['iso_code', 'year'])
#unique_countries = unique_countries.replace({np.nan: None})
for index, row in energy_df.iterrows():
    cursor.execute("INSERT INTO energy_stats (iso_code,country,year,population,gdp,biofuel_cons_per_capita,biofuel_consumption,biofuel_electricity,biofuel_share_elec,carbon_intensity_elec,coal_cons_per_capita,coal_consumption,coal_electricity,coal_production,coal_share_elec,electricity_demand,electricity_generation,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,gas_consumption,gas_energy_per_capita,gas_production,gas_share_elec,greenhouse_gas_emissions,low_carbon_consumption,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,nuclear_consumption,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,oil_consumption,oil_electricity,oil_energy_per_capita,oil_production,oil_share_elec,other_renewable_consumption,other_renewable_electricity,other_renewables_energy_per_capita,other_renewables_share_elec,renewables_consumption,renewables_electricity,renewables_energy_per_capita,renewables_share_elec) VALUES (%s, %s)", (row['iso_code'],row['country'],))

In [298]:
energy_df = nf[['iso_code','year','population','gdp','biofuel_cons_per_capita','biofuel_consumption','biofuel_electricity','biofuel_share_elec','carbon_intensity_elec','coal_cons_per_capita','coal_consumption','coal_electricity','coal_production','coal_share_elec','electricity_demand',
'electricity_generation','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','gas_consumption','gas_energy_per_capita','gas_production',
'gas_share_elec','greenhouse_gas_emissions','low_carbon_consumption','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','nuclear_consumption','nuclear_electricity','nuclear_energy_per_capita',
'nuclear_share_elec','oil_consumption','oil_electricity','oil_energy_per_capita','oil_production','oil_share_elec','other_renewable_consumption','other_renewable_electricity','other_renewables_energy_per_capita',
'other_renewables_share_elec','renewables_consumption','renewables_electricity','renewables_energy_per_capita','renewables_share_elec']]

In [326]:
from tqdm import tqdm
def insert_energy_stats_bulk(df, cursor, conn, columns=None, batch_size=500):

    # Default energy columns if not specified
    if columns is None:
        columns = ['iso_code','year','population','gdp','biofuel_cons_per_capita','biofuel_consumption','biofuel_electricity','biofuel_share_elec','carbon_intensity_elec','coal_cons_per_capita','coal_consumption','coal_electricity','coal_production','coal_share_elec','electricity_demand',
'electricity_generation','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','gas_consumption','gas_energy_per_capita','gas_production',
'gas_share_elec','greenhouse_gas_emissions','low_carbon_consumption','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','nuclear_consumption','nuclear_electricity','nuclear_energy_per_capita',
'nuclear_share_elec','oil_consumption','oil_electricity','oil_energy_per_capita','oil_production','oil_share_elec','other_renewable_consumption','other_renewable_electricity','other_renewables_energy_per_capita',
'other_renewables_share_elec','renewables_consumption','renewables_electricity','renewables_energy_per_capita','renewables_share_elec']
    
    # Keep only relevant columns
    energy_df = df[columns].copy()
    
    # Drop rows without iso_code or year (essential keys)
    energy_df = energy_df.dropna(subset=['iso_code', 'year'])
    energy_df = energy_df.replace({np.nan: None})
    
    print("Inserting energy stats into database...")

    placeholders = ', '.join(['%s'] * len(columns))
    col_names = ', '.join(columns)
    
    count = 0

    for _, row in tqdm(energy_df.iterrows(), total=len(energy_df)):
        try:
            values = [row[col] for col in columns]
            cursor.execute(f"""
                INSERT INTO energy_stats ({col_names})
                VALUES ({placeholders})
            """, values)
            count += 1

            if count % batch_size == 0:
                conn.commit()

        except Exception as e:
            print(f"Error inserting row: {e}")

    conn.commit()
    print(f"Inserted successfully. Total rows inserted: {count}")

In [324]:
energy_cols = ['iso_code','year','population','gdp','biofuel_cons_per_capita','biofuel_consumption','biofuel_electricity','biofuel_share_elec','carbon_intensity_elec','coal_cons_per_capita','coal_consumption','coal_electricity','coal_production','coal_share_elec','electricity_demand',
'electricity_generation','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','gas_consumption','gas_energy_per_capita','gas_production',
'gas_share_elec','greenhouse_gas_emissions','low_carbon_consumption','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','nuclear_consumption','nuclear_electricity','nuclear_energy_per_capita',
'nuclear_share_elec','oil_consumption','oil_electricity','oil_energy_per_capita','oil_production','oil_share_elec','other_renewable_consumption','other_renewable_electricity','other_renewables_energy_per_capita',
'other_renewables_share_elec','renewables_consumption','renewables_electricity','renewables_energy_per_capita','renewables_share_elec']
insert_energy_stats_bulk(energy_df, cursor, conn, columns=energy_cols)

Inserting energy stats into database...

100%|████████████████████████████████████████████████████████████████████████████| 5118/5118 [00:02<00:00, 1747.13it/s]

Insert complete. Total rows inserted: 5118